
package Sistema_Registros_Mascotas;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class Cargar_Registros extends javax.swing.JFrame {

    /**
     * Creates new form Cargar_Registros
     */
    public Cargar_Registros() {
        initComponents();
        CargarTabla();
         
       txtbusquedadu.getDocument().addDocumentListener(new DocumentListener() {
    @Override
    public void insertUpdate(DocumentEvent e) {
         CargarTabla(); // Método para ejecutar la búsqueda
    }

     @Override
    public void removeUpdate(DocumentEvent e) {
         CargarTabla(); // Método para ejecutar la búsqueda
    }

     @Override
    public void changedUpdate(DocumentEvent e) {
        CargarTabla(); // Método para ejecutar la búsqueda
    }
});
       txtBusMas.getDocument().addDocumentListener(new DocumentListener() {
    @Override
    public void insertUpdate(DocumentEvent e) {
         CargarTabla(); // Método para ejecutar la búsqueda
    }

     @Override
    public void removeUpdate(DocumentEvent e) {
         CargarTabla(); // Método para ejecutar la búsqueda
    }

     @Override
    public void changedUpdate(DocumentEvent e) {
        CargarTabla(); // Método para ejecutar la búsqueda
    }
});
    }
private void CargarTabla(){
    
     DefaultTableModel modeloTabla = (DefaultTableModel) tlbDatos.getModel();
        modeloTabla.setRowCount(0);
        PreparedStatement ps1;
        
        ResultSet rs;
       
        try {
            Connection con = conexion.getconexion();
            ps1 = con.prepareStatement("SELECT \n" +
"    CONCAT(DT.Nombre_Dueño, ' ', DT.Apellido_Paterno_Dueño, ' ', DT.Apellido_Materno_Dueño) AS Nombre_Completo_Dueño,\n" +
"   D.ID_Mascota,DT.ID_Dueño ,D.Nombre_Mascota AS Nombre_Mascota,\n" +
"    D.Color_Mascota AS Color_Mascota,\n" +
"    D.Atencion_Especial AS Atencion_Especial,\n" +
"    D.Señales_Particulares AS Señales_Particulares,\n" +
"    CASE\n" +
"        WHEN D.ID_TMascota = 1 THEN 'Perro'\n" +
"        WHEN D.ID_TMascota = 2 THEN 'Gato'\n" +
"        ELSE 'Desconocido'\n" +
"    END AS Tipo_Mascota,\n" +
"    CASE\n" +
"        WHEN D.ID_TMascota = 1 THEN RP.Raza_Perro\n" +
"        WHEN D.ID_TMascota = 2 THEN RG.Raza_Gatos\n" +
"        ELSE 'Desconocida'\n" +
"    END AS Raza\n" +
"FROM Datos_Mascotas D\n" +
"JOIN Tipo_Mascota TM ON D.ID_TMascota = TM.ID_TMascota\n" +
"LEFT JOIN Raza_Perros RP ON D.ID_RazaP = RP.ID_Raza_Perros AND D.ID_TMascota = 1\n" +
"LEFT JOIN Raza_Gatos RG ON D.ID_RazaG = RG.ID_Raza_Gatos AND D.ID_TMascota = 2\n" +
"JOIN Dueños DT ON D.ID_Dueño_De_Mascota = DT.ID_Dueño WHERE Nombre_Dueño like ? AND Nombre_Mascota like ?;");
               ps1.setString(1, "%" + txtbusquedadu.getText() + "%");
               ps1.setString(2, "%" +txtBusMas.getText() + "%");
            rs = ps1.executeQuery();
          
            
             
            
            while (rs.next()) {
                 
                
                
                Object[] fila = new Object[6]; 
           fila[0] = rs.getObject("ID_Dueño");
            fila[1] = rs.getObject("Nombre_Completo_Dueño");
            fila[2] = rs.getObject("ID_Mascota");
             fila[3] = rs.getObject("Tipo_Mascota");
                
              fila[4] = rs.getObject("Nombre_Mascota");
                
             fila[5] = rs.getObject("Raza");
                
                



                modeloTabla.addRow(fila);
                
                
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
         
        
}
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tlbDatos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtbusquedadu = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBusMas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tlbDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre dueño", "ID", "Tipo de mascota", "Nombre Mascota", "Raza"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tlbDatos);
        if (tlbDatos.getColumnModel().getColumnCount() > 0) {
            tlbDatos.getColumnModel().getColumn(0).setPreferredWidth(10);
            tlbDatos.getColumnModel().getColumn(2).setPreferredWidth(10);
        }

        jButton1.setText("Menu Principal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Panel de busquedas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 2, 14))); // NOI18N

        jLabel1.setText("Busqueda Nombre dueño");

        jLabel2.setText("Busqueda Nombre mascota");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtbusquedadu, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBusMas, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(421, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbusquedadu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBusMas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(55, 55, 55))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      Menu_Principal abrir =new  Menu_Principal();
       abrir.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cargar_Registros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cargar_Registros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cargar_Registros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cargar_Registros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cargar_Registros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tlbDatos;
    private javax.swing.JTextField txtBusMas;
    private javax.swing.JTextField txtbusquedadu;
    // End of variables declaration//GEN-END:variables
}
