/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Sistema_Registros_Mascotas;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class Registro_Dueños extends javax.swing.JFrame {

    /**
     * Creates new form Registro_Dueños
     */
    public Registro_Dueños() {
        initComponents();
        txtidu.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombreD = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtApelpa = new javax.swing.JTextField();
        ji = new javax.swing.JLabel();
        txtapelma = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCalle = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtColonia = new javax.swing.JTextField();
        as = new javax.swing.JLabel();
        txtCP = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMun = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtidu = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro de Dueños", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 2, 14))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel1.setText("Nombre:");

        txtNombreD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreDKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel2.setText("Apellido Paterno:");

        txtApelpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApelpaActionPerformed(evt);
            }
        });
        txtApelpa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApelpaKeyTyped(evt);
            }
        });

        ji.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        ji.setText("Apellido Materno:");

        txtapelma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapelmaKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel3.setText("Datos de contacto");

        jLabel4.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel4.setText("Telefono:");

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel5.setText("Correo:");

        txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCorreoKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel6.setText("Informacion de Direccion");

        jLabel7.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel7.setText("Calle:");

        txtCalle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCalleKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel8.setText("Colonia:");

        as.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        as.setText("Codigo Postal:");

        txtCP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCPKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel9.setText("Municipio:");

        jLabel10.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel10.setText("Estado:");

        txtMun.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMunKeyTyped(evt);
            }
        });

        txtEstado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEstadoKeyTyped(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/limpiar.png"))); // NOI18N
        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cargar.jpg"))); // NOI18N
        jButton3.setText("Cargar datos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/modificar.png"))); // NOI18N
        jButton4.setText("Modificar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MP.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombreD, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtApelpa, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ji)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtapelma, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addComponent(txtidu, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton4))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtMun, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtEstado)))
                                    .addGap(211, 211, 211))))
                        .addGap(0, 18, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCalle))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtColonia))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(as)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCP, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNombreD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtidu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtApelpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ji)
                            .addComponent(txtapelma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton5))
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtColonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(as)
                            .addComponent(txtCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtMun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(3, 3, 3)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            String [] opciones = { "Si,estoy seguro", " No", "Cancelar" };
 

String Nombre = txtNombreD.getText();

int Seleccion = JOptionPane.showOptionDialog (null, " Estas seguro de querer almacenar el registro de "+Nombre+" ?,!Recuerda revisar los bien los datos :D!", "Selecciona una opcion", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null/*icono*/, opciones, opciones[0]);
       
        if (Seleccion==0){
        
        
        String Apelpa = txtApelpa.getText();
        String Apelma = txtapelma.getText();
       
       
        
        Long Telefono = Long.parseLong(txtTelefono.getText());
        String Correo = txtCorreo.getText();
        String Calle = txtCalle.getText();
        int CP = Integer.parseInt(txtCP.getText());
        String Colonia = txtColonia.getText();
        String Mun = txtMun.getText();
        String Estado = txtEstado.getText();
    Connection con = conexion.getconexion();
        try (PreparedStatement ps = con.prepareStatement("INSERT INTO Dueños (Nombre_Dueño,Apellido_Paterno_Dueño,Apellido_Materno_Dueño,Telefono_Dueño,Correo_Dueño,Calle_Dueño,Colonia_Dueño,Codigo_Postal_Dueño,Municipio_Dueño,Estado_Dueño)VALUES(?,?,?,?,?,?,?,?,?,?)", PreparedStatement.RETURN_GENERATED_KEYS)){
        
            
            ps.setString(1, Nombre);
            ps.setString(2, Apelpa);
            ps.setString(3, Apelma);
           
            ps.setLong(4, Telefono);
            ps.setString(5, Correo);
            ps.setString(6, Calle);
            
            ps.setString(7, Colonia);
            ps.setInt(8, CP);
            ps.setString(9, Mun);
            ps.setString(10, Estado);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Registro guardado :D");
            
            int idus;
                try (ResultSet rs = ps.getGeneratedKeys()) {
                    if (rs.next()) {
                        idus = rs.getInt(1);
                    } else {
                        throw new SQLException("No se pudo obtener el ID del préstamo insertado.");
                    }
                }
               
           JOptionPane.showMessageDialog(null, "Tu numero de Dueño es: "+idus+"");
  limpiar();
                    
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
            
        }
        
        }else{
            JOptionPane.showMessageDialog(null, "Operacion cancelada");
            
        }
        limpiar();
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        limpiar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       String idus=null;
        idus = JOptionPane.showInputDialog(null, "Ingresa ID de usuario:");
        int Idus=Integer.parseInt(idus);
         txtidu.setText(idus);
        PreparedStatement ps;
            ResultSet rs;
    try {
            Connection con = conexion.getconexion();
            ps = con.prepareStatement("SELECT*FROM Dueños WHERE ID_Dueño=?");
            ps.setInt(1, Idus);
                       
          rs = ps.executeQuery();
            while(rs.next()){
                
           txtNombreD.setText(rs.getString("Nombre_Dueño"));
            txtApelpa.setText(rs.getString("Apellido_Paterno_Dueño"));
            txtapelma.setText(rs.getString("Apellido_Materno_Dueño"));
           txtTelefono.setText(rs.getString("Telefono_Dueño"));
            txtCorreo.setText(rs.getString("Correo_Dueño"));
            txtCalle.setText(rs.getString("Calle_Dueño"));
              txtColonia.setText(rs.getString("Colonia_Dueño"));
                txtCP.setText(rs.getString("Codigo_Postal_Dueño"));
               txtEstado.setText(rs.getString("Estado_Dueño"));
               txtMun.setText(rs.getString("Municipio_Dueño"));
               
       

            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
            
        }
        
       
             
            
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         String [] opciones = { "Si,estoy seguro", " No", "Cancelar" };
 

String Nombre = txtNombreD.getText();
String idus=txtidu.getText();
int Seleccion = JOptionPane.showOptionDialog (null, " Estas seguro de querer modificar el registro de "+Nombre+" ?", "Selecciona una opcion", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null/*icono*/, opciones, opciones[0]);
       
        if (Seleccion==0){
            
        
        
       
          
  
        
       
        
        
        String Apelpa = txtApelpa.getText();
        String Apelma = txtapelma.getText();
      
       
       
        Long Telefono = Long.parseLong(txtTelefono.getText());
        String Correo = txtCorreo.getText();
        String Calle = txtCalle.getText();
        int CP = Integer.parseInt(txtCP.getText());
        String Colonia = txtColonia.getText();
        String Mun = txtMun.getText();
        String Estado = txtEstado.getText();
        
        try {
            Connection con = conexion.getconexion();
            PreparedStatement ps = con.prepareStatement("UPDATE  Dueños SET Nombre_Dueño=?,Apellido_Paterno_Dueño=?,Apellido_Materno_Dueño=?,Telefono_Dueño=?,Correo_Dueño=?,Calle_Dueño=?,Colonia_Dueño=?,Codigo_Postal_Dueño=?,Municipio_Dueño=?,Estado_Dueño=? WHERE ID_Dueño=?");
            ps.setString(1, Nombre);
            ps.setString(2, Apelpa);
            ps.setString(3, Apelma);
         
            ps.setLong(4, Telefono);
            ps.setString(5, Correo);
            ps.setString(6, Calle);
            ps.setString(7, Colonia);
            ps.setInt(8, CP);
            
            ps.setString(9, Mun);
            ps.setString(10, Estado);
            ps.setString(11, idus);
            
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Registro Modificado :D");
            limpiar();
       
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
            
        }
        }
        else{
            JOptionPane.showMessageDialog(null, "Operacion Cancelada ");
             
            limpiar();
          
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         Menu_Principal abrir =new  Menu_Principal();
       abrir.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
      char c = evt.getKeyChar();
                if (!Character.isDigit(c)) { 
                    evt.consume();
                }
        if(txtTelefono.getText().length() >= 10)
    {
        evt.consume();
        Toolkit.getDefaultToolkit().beep();
        JOptionPane.showMessageDialog(
            null, 
            "Solo se permiten 10 números", 
            "Advertencia", 
            JOptionPane.WARNING_MESSAGE, 
            null);}
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtCPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCPKeyTyped
        char c = evt.getKeyChar();
                if (!Character.isDigit(c)) { 
                    evt.consume();
                }
        if(txtCP.getText().length() >= 5)
    {
        evt.consume();
        Toolkit.getDefaultToolkit().beep();
        JOptionPane.showMessageDialog(
            null, 
            "El codigo postal solo se compone de 5 digitos :D", 
            "Advertencia", 
            JOptionPane.WARNING_MESSAGE, 
            null);}
    }//GEN-LAST:event_txtCPKeyTyped

    private void txtNombreDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreDKeyTyped
       char c = evt.getKeyChar();
                if (!Character.isLetter(c)&& c != ' ') { 
                    evt.consume();
                }
        if(txtNombreD.getText().length() >= 30)
    {
        evt.consume();
        Toolkit.getDefaultToolkit().beep();
        JOptionPane.showMessageDialog(
            null, 
            "Solo se permiten 30 caracteres", 
            "Advertencia", 
            JOptionPane.WARNING_MESSAGE, 
            null);}
    }//GEN-LAST:event_txtNombreDKeyTyped

    private void txtApelpaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApelpaKeyTyped
           char c = evt.getKeyChar();
                if (!Character.isLetter(c)&& c != ' ') { 
                    evt.consume();
                }
        if(txtApelpa.getText().length() >= 30)
    {
        evt.consume();
        Toolkit.getDefaultToolkit().beep();
        JOptionPane.showMessageDialog(
            null, 
            "Solo se permiten 30 caracteres", 
            "Advertencia", 
            JOptionPane.WARNING_MESSAGE, 
            null);}
    }//GEN-LAST:event_txtApelpaKeyTyped

    private void txtapelmaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapelmaKeyTyped
         char c = evt.getKeyChar();
                if (!Character.isLetter(c)&& c != ' ') { 
                    evt.consume();
                }
        if(txtapelma.getText().length() >= 30)
    {
        evt.consume();
        Toolkit.getDefaultToolkit().beep();
        JOptionPane.showMessageDialog(
            null, 
            "Solo se permiten 30 caracteres", 
            "Advertencia", 
            JOptionPane.WARNING_MESSAGE, 
            null);}
    }//GEN-LAST:event_txtapelmaKeyTyped

    private void txtCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyTyped
         char c = evt.getKeyChar();
                if (!Character.isLetterOrDigit(c)&& c != ' ' && c!='@'&& c!='_'&& c!='-'&& c!='.') { 
                    evt.consume();
                }
        if(txtCorreo.getText().length() >= 40)
    {
        evt.consume();
        Toolkit.getDefaultToolkit().beep();
        JOptionPane.showMessageDialog(
            null, 
            "Solo se permiten 40 caracteres", 
            "Advertencia", 
            JOptionPane.WARNING_MESSAGE, 
            null);}
    }//GEN-LAST:event_txtCorreoKeyTyped

    private void txtCalleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCalleKeyTyped
         char c = evt.getKeyChar();
                if (!Character.isLetterOrDigit(c)&& c != ' ') { 
                    evt.consume();
                }
        if(txtCalle.getText().length() >= 40)
    {
        evt.consume();
        Toolkit.getDefaultToolkit().beep();
        JOptionPane.showMessageDialog(
            null, 
            "Solo se permiten 40 caracteres", 
            "Advertencia", 
            JOptionPane.WARNING_MESSAGE, 
            null);}
    }//GEN-LAST:event_txtCalleKeyTyped

    private void txtMunKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMunKeyTyped
       char c = evt.getKeyChar();
                if (!Character.isLetter(c)&& c != ' ') { 
                    evt.consume();
                }
        if(txtMun.getText().length() >= 40)
    {
        evt.consume();
        Toolkit.getDefaultToolkit().beep();
        JOptionPane.showMessageDialog(
            null, 
            "Solo se permiten 40 caracteres", 
            "Advertencia", 
            JOptionPane.WARNING_MESSAGE, 
            null);}
    }//GEN-LAST:event_txtMunKeyTyped

    private void txtEstadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstadoKeyTyped
      char c = evt.getKeyChar();
                if (!Character.isLetter(c)&& c != ' ') { 
                    evt.consume();
                }
        if(txtEstado.getText().length() >= 35)
    {
        evt.consume();
        Toolkit.getDefaultToolkit().beep();
        JOptionPane.showMessageDialog(
            null, 
            "Solo se permiten 35 caracteres", 
            "Advertencia", 
            JOptionPane.WARNING_MESSAGE, 
            null);}
    }//GEN-LAST:event_txtEstadoKeyTyped

    private void txtApelpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApelpaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApelpaActionPerformed
 private void limpiar() {
        
        txtNombreD.setText("");
        txtApelpa.setText("");
        txtapelma.setText("");
        
        txtTelefono.setText("");
        txtMun.setText("");
        txtEstado.setText("");
        txtCP.setText("");
        txtCorreo.setText("");
        txtCalle.setText("");
        txtColonia.setText("");
        txtidu.setText("");
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_Dueños.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_Dueños.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_Dueños.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_Dueños.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_Dueños().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel as;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel ji;
    private javax.swing.JTextField txtApelpa;
    private javax.swing.JTextField txtCP;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtColonia;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtMun;
    private javax.swing.JTextField txtNombreD;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtapelma;
    private javax.swing.JTextField txtidu;
    // End of variables declaration//GEN-END:variables
}
